steps:

  - id: 'install dependencies'
    name: 'node:14.15.0'
    args: [ "npm","--experimental-modules","install" ]
    waitFor:
      - '-'

  - id: 'prepare env file'
    name: 'alpine'
    entrypoint: sh
    args:
      - '-c'
      - |
        sed -i -e "s#target: 'your pre url',#target: '${_API_URL}',#g" config/proxy.ts
      
    waitFor:
      - '-'

  - id: 'build release'
    name: 'node:14.15.0'
    args: [ "yarn","build" ]
    waitFor:
      - 'prepare env file'
      - 'install dependencies'

  - id: 'clear DEMO storage before new release'
    name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', '-q', 'rm', '-rf', "gs://${_STORAGE}/**"]
    waitFor:
      - 'build release'

  - id: 'push to DEMO storage'
    name: 'gcr.io/cloud-builders/gsutil'
    args: ['-h', 'Cache-Control:no-cache,max-age=0','-m', 'cp', '-r', './dist/*', 'gs://${_STORAGE}/lxp/']
    waitFor:
      - 'clear DEMO storage before new release'

  - id: 'add public access'
    name: 'gcr.io/cloud-builders/gsutil'
    args: ['acl', 'ch', '-u', 'AllUsers:R', '-r', 'gs://${_STORAGE}/*']
    waitFor:
      - 'push to DEMO storage'